@url-apiKey = https://mi6y7aitog.execute-api.us-east-1.amazonaws.com/dev
@url = https://38xd6o3h33.execute-api.us-east-1.amazonaws.com/


###
GET {{url-apiKey}}/get-user/1234
x-api-key: rdYeRRxg9W2KXvMRk45to39EsEQRRscK7x4PCh1F

###
GET {{url}}/player-score

###
GET {{url}}/player-score/2b90f3d9-20d4-44e8-b71e-6eadf6e044cd

###
POST {{url}}/player-score
Content-Type: application/json

{
    "name": "Idan",
    "score": 20,
    "game": "football"
}

###
PATCH {{url}}/player-score/2b90f3d9-20d4-44e8-b71e-6eadf6e044cd
Content-Type: application/json

{
    "score": 44
}


###
DELETE {{url}}/player-score/3e32fe18-1a6a-4542-89ad-0f6a48a387b2

###
GET {{url}}/game-scores/tennis



###
GET {{url}}/file/car.json

###
POST {{url}}/file/car.json
Content-Type: application/json

{
    "model": "Ford Focus",
    "year": 2023,
    "color": "red"
}

###
POST {{url}}/send-email
Content-Type: application/json

{
    "from": "nir.gluzman@gmail.com",
    "to": "esty101@gmail.com",
    "subject": "hello from Serverless",
    "text": "bla bla"
}
