@url = https://48zi8xqjfh.execute-api.us-east-1.amazonaws.com/

###
GET {{url}}/player-score

###
GET {{url}}/player-score/58dbde8e-01af-404c-bddf-d8ee041aab43

###
POST {{url}}/player-score
Content-Type: application/json

{
    "name": "Klaus",
    "score": 23
}

###
DELETE {{url}}/player-score/58dbde8e-01af-404c-bddf-d8ee041aab43

###
GET {{url}}/file/car.json

###
POST {{url}}/file/car.json
Content-Type: application/json

{
    "model": "Ford Focus",
    "year": 2023,
    "color": "red"
}
